
package com.affirm.efectiva.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceMovilCMESoap", targetNamespace = "http://ws_NCanales_movil/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceMovilCMESoap {


    /**
     * 
     * @param datos
     * @return
     *     returns com.affirm.efectiva.client.ArrayOfMovilCMERpt
     */
    @WebMethod(operationName = "wm_interface_cme_movil", action = "http://ws_NCanales_movil/wm_interface_cme_movil")
    @WebResult(name = "wm_interface_cme_movilResult", targetNamespace = "http://ws_NCanales_movil/")
    @RequestWrapper(localName = "wm_interface_cme_movil", targetNamespace = "http://ws_NCanales_movil/", className = "com.affirm.efectiva.client.WmInterfaceCmeMovil")
    @ResponseWrapper(localName = "wm_interface_cme_movilResponse", targetNamespace = "http://ws_NCanales_movil/", className = "com.affirm.efectiva.client.WmInterfaceCmeMovilResponse")
    public ArrayOfMovilCMERpt wmInterfaceCmeMovil(
        @WebParam(name = "datos", targetNamespace = "http://ws_NCanales_movil/")
        MovilCMESlc datos);

}
