
package com.affirm.abaco.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CreditoFault", targetNamespace = "http://servicio.ws/")
public class CreditoException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ECreditoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CreditoException(String message, ECreditoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CreditoException(String message, ECreditoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.affirm.abaco.client.ECreditoFault
     */
    public ECreditoFault getFaultInfo() {
        return faultInfo;
    }

}
