
package com.affirm.abaco.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCredito", targetNamespace = "http://servicio.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCredito {


    /**
     * 
     * @param entidadCredito
     * @return
     *     returns com.affirm.abaco.client.ERptaCredito
     * @throws CreditoException
     */
    @WebMethod
    @WebResult(name = "rptaCredito", targetNamespace = "")
    @RequestWrapper(localName = "crearCredito", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.CrearCredito")
    @ResponseWrapper(localName = "crearCreditoResponse", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.CrearCreditoResponse")
    public ERptaCredito crearCredito(
        @WebParam(name = "entidadCredito", targetNamespace = "")
        ECredito entidadCredito)
        throws CreditoException
    ;

    /**
     * 
     * @param entidadSocio
     * @return
     *     returns com.affirm.abaco.client.EMensaje
     * @throws CreditoException
     */
    @WebMethod
    @WebResult(name = "rptaMensaje", targetNamespace = "")
    @RequestWrapper(localName = "crearSocio", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.CrearSocio")
    @ResponseWrapper(localName = "crearSocioResponse", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.CrearSocioResponse")
    public EMensaje crearSocio(
        @WebParam(name = "entidadSocio", targetNamespace = "")
        ESocio entidadSocio)
        throws CreditoException
    ;

    /**
     * 
     * @param tipoDocumento
     * @param documento
     * @return
     *     returns com.affirm.abaco.client.ERptaCredito
     * @throws CreditoException
     */
    @WebMethod
    @WebResult(name = "rptaCredito", targetNamespace = "")
    @RequestWrapper(localName = "esSocio", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.EsSocio")
    @ResponseWrapper(localName = "esSocioResponse", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.EsSocioResponse")
    public ERptaCredito esSocio(
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "documento", targetNamespace = "")
        String documento)
        throws CreditoException
    ;

    /**
     * 
     * @param entidadSocio
     * @return
     *     returns com.affirm.abaco.client.EMensaje
     * @throws CreditoException
     */
    @WebMethod
    @WebResult(name = "rptaMensaje", targetNamespace = "")
    @RequestWrapper(localName = "actualizarSocio", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.ActualizarSocio")
    @ResponseWrapper(localName = "actualizarSocioResponse", targetNamespace = "http://servicio.ws/", className = "com.affirm.abaco.client.ActualizarSocioResponse")
    public EMensaje actualizarSocio(
        @WebParam(name = "entidadSocio", targetNamespace = "")
        ESocio entidadSocio)
        throws CreditoException
    ;

}
