
package com.affirm.sentinel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws_senestliteRSA", targetNamespace = "PrivadoE2Cliente", wsdlLocation = "https://www2.sentinelperu.com/wsevo2/aws_senestlitersa.aspx?wsdl")
public class WsSenestliteRSA
    extends Service
{

    private final static URL WSSENESTLITERSA_WSDL_LOCATION;
    private final static WebServiceException WSSENESTLITERSA_EXCEPTION;
    private final static QName WSSENESTLITERSA_QNAME = new QName("PrivadoE2Cliente", "ws_senestliteRSA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(System.getenv("SENTINEL_URL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSENESTLITERSA_WSDL_LOCATION = url;
        WSSENESTLITERSA_EXCEPTION = e;
    }

    public WsSenestliteRSA() {
        super(__getWsdlLocation(), WSSENESTLITERSA_QNAME);
    }

    public WsSenestliteRSA(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSENESTLITERSA_QNAME, features);
    }

    public WsSenestliteRSA(URL wsdlLocation) {
        super(wsdlLocation, WSSENESTLITERSA_QNAME);
    }

    public WsSenestliteRSA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSENESTLITERSA_QNAME, features);
    }

    public WsSenestliteRSA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSenestliteRSA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsSenestliteRSASoapPort
     */
    @WebEndpoint(name = "ws_senestliteRSASoapPort")
    public WsSenestliteRSASoapPort getWsSenestliteRSASoapPort() {
        return super.getPort(new QName("PrivadoE2Cliente", "ws_senestliteRSASoapPort"), WsSenestliteRSASoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSenestliteRSASoapPort
     */
    @WebEndpoint(name = "ws_senestliteRSASoapPort")
    public WsSenestliteRSASoapPort getWsSenestliteRSASoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("PrivadoE2Cliente", "ws_senestliteRSASoapPort"), WsSenestliteRSASoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSENESTLITERSA_EXCEPTION!= null) {
            throw WSSENESTLITERSA_EXCEPTION;
        }
        return WSSENESTLITERSA_WSDL_LOCATION;
    }

}
