
package com.affirm.sentinel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ws_senestliteRSASoapPort", targetNamespace = "PrivadoE2Cliente")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSenestliteRSASoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.affirm.sentinel.WsSenestliteRSAExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "PrivadoE2Clienteaction/AWS_SENESTLITERSA.Execute")
    @WebResult(name = "ws_senestliteRSA.ExecuteResponse", targetNamespace = "PrivadoE2Cliente", partName = "parameters")
    public WsSenestliteRSAExecuteResponse execute(
        @WebParam(name = "ws_senestliteRSA.Execute", targetNamespace = "PrivadoE2Cliente", partName = "parameters")
        WsSenestliteRSAExecute parameters);

}
