
package com.affirm.sentinel.infpri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_SentinelInfPriSoapPort", targetNamespace = "PrivadoE2Cliente")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSSentinelInfPriSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.affirm.sentinel.infpri.WSSentinelInfPriExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "PrivadoE2Clienteaction/AWS_SENTINELINFPRI.Execute")
    @WebResult(name = "WS_SentinelInfPri.ExecuteResponse", targetNamespace = "PrivadoE2Cliente", partName = "parameters")
    public WSSentinelInfPriExecuteResponse execute(
        @WebParam(name = "WS_SentinelInfPri.Execute", targetNamespace = "PrivadoE2Cliente", partName = "parameters")
        WSSentinelInfPriExecute parameters);

}
