
package com.affirm.sentinel.infpri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_SentinelInfPri", targetNamespace = "PrivadoE2Cliente", wsdlLocation = "https://www2.sentinelperu.com/wsevo2/aws_sentinelinfpri.aspx?wsdl")
public class WSSentinelInfPri
    extends Service
{

    private final static URL WSSENTINELINFPRI_WSDL_LOCATION;
    private final static WebServiceException WSSENTINELINFPRI_EXCEPTION;
    private final static QName WSSENTINELINFPRI_QNAME = new QName("PrivadoE2Cliente", "WS_SentinelInfPri");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(System.getenv("SENTINEL_INF_PRI_URL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSENTINELINFPRI_WSDL_LOCATION = url;
        WSSENTINELINFPRI_EXCEPTION = e;
    }

    public WSSentinelInfPri() {
        super(__getWsdlLocation(), WSSENTINELINFPRI_QNAME);
    }

    public WSSentinelInfPri(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSENTINELINFPRI_QNAME, features);
    }

    public WSSentinelInfPri(URL wsdlLocation) {
        super(wsdlLocation, WSSENTINELINFPRI_QNAME);
    }

    public WSSentinelInfPri(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSENTINELINFPRI_QNAME, features);
    }

    public WSSentinelInfPri(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSentinelInfPri(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSSentinelInfPriSoapPort
     */
    @WebEndpoint(name = "WS_SentinelInfPriSoapPort")
    public WSSentinelInfPriSoapPort getWSSentinelInfPriSoapPort() {
        return super.getPort(new QName("PrivadoE2Cliente", "WS_SentinelInfPriSoapPort"), WSSentinelInfPriSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSentinelInfPriSoapPort
     */
    @WebEndpoint(name = "WS_SentinelInfPriSoapPort")
    public WSSentinelInfPriSoapPort getWSSentinelInfPriSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("PrivadoE2Cliente", "WS_SentinelInfPriSoapPort"), WSSentinelInfPriSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSENTINELINFPRI_EXCEPTION!= null) {
            throw WSSENTINELINFPRI_EXCEPTION;
        }
        return WSSENTINELINFPRI_WSDL_LOCATION;
    }

}
