package com.affirm.jobs.webscrapper;

import com.DeathByCaptcha.Captcha;
import com.affirm.common.model.catalog.Proxy;
import com.affirm.common.model.transactional.EssaludResult;
import org.apache.commons.lang3.StringUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.util.List;

/**
 * Created by john on 29/09/16.
 */
public class EssaludScrapper extends Scrapper {

    private final static String URL = "http://ww4.essalud.gob.pe:7777/acredita/";
    private final static String WRONG_CAPTCHA_ESSALUD = "El id es incorrecto, intente nuevamente";

    public EssaludScrapper(String user, String password, int timeout) {
        super(user, password, timeout);
    }

    public EssaludScrapper(String user, String password, int timeout, Proxy proxy) {
        super(user, password, timeout, proxy);
    }

    public EssaludResult getData(Integer docType, String docNumber) throws Exception {
        System.out.println("DOCNUMBER " + docNumber);
        EssaludResult result = new EssaludResult();

        try {
            openSite(URL);
            System.out.println("OPENED");
        } catch (TimeoutException e) {
            e.printStackTrace();
            return null;
        }

        int tries = 1;

        File imageCaptcha;
        Captcha solved = null;

        do {

            if (tries >= 5) {
                System.out.println("Se hicieron 4 intentos");
                return null;
            } else if (tries > 1) {
                System.out.println("fallo el Captcha");
                reportCaptcha(solved);
            }

            WebDriverWait waiter = new WebDriverWait(driver, 90);
            WebElement form;
            Select selectBuscarPor = new Select(waiter.until(ExpectedConditions.elementToBeClickable(By.id("BuscarPor"))));
            selectBuscarPor.selectByValue("tdocumento");

            try {
                form = waiter.until(ExpectedConditions.presenceOfElementLocated(By.name("formin2")));
            } catch (TimeoutException | NoSuchElementException e) {
                // Reopen
                openSite(URL);
                form = waiter.until(ExpectedConditions.presenceOfElementLocated(By.name("formin2")));
            }

            Select selectTipoDocumento = new Select(form.findElement(By.name("td")));
            selectTipoDocumento.selectByValue("1");

            form.findElement(By.name("nd")).clear();
            form.findElement(By.name("nd")).sendKeys(docNumber);
            WebElement captcha = form.findElement(By.tagName("img"));
            imageCaptcha = shootWebElement(captcha);
            solved = solveCaptcha(imageCaptcha);
            driver.findElement(By.name("captchafield_doc")).sendKeys(StringUtils.upperCase(solved.text));
            form.submit();

            try {
                driver.switchTo().alert().dismiss();
            } catch (Exception e){
            }

            tries++;

        } while (driver.getTitle().equals("Ingreso de condiciones"));

        System.out.println("driver.getTitle() " + driver.getTitle());


        if (driver.findElementsByName("frmCond").size() >= 1) {
            WebElement formResult = driver.findElement(By.name("frmCond"));
            WebElement tableResult = formResult.findElement(By.tagName("table"));
            System.out.println("Llegué Aquí");
            List rows = tableResult.findElements(By.tagName("td").className("tdDetRigth"));

            for (int i = 0; i < rows.size(); i++) {
                WebElement row = (WebElement) rows.get(i);
                System.out.println("row.getText(" + i + ")" + row.getText());
            }

            result.setFullName(((WebElement) rows.get(0)).getText());
            result.setDocumentNumber(((WebElement) rows.get(1)).getText());
            result.setInssuredType(((WebElement) rows.get(2)).getText());
            result.setAutogeneratedID(((WebElement) rows.get(3)).getText());
            result.setInssuranceType(((WebElement) rows.get(5)).getText());
            result.setHealthCenter(((WebElement) rows.get(6)).getText());
            result.setHealthCenterAddress(((WebElement) rows.get(8)).getText());
            result.setSince(EssaludResult.DATE_FORMAT.parse(((WebElement) rows.get(7)).getText()));
            result.setUntil(EssaludResult.DATE_FORMAT.parse(((WebElement) rows.get(9)).getText()));
            result.setAfiliatedTo(((WebElement) rows.get(10)).getText());

            System.out.println("RESULT " + result.toString());

            return result;

        } else {
            System.out.println("No se encuentra en la base de ESSALUD");
            return result;

        }
    }

    public static void main(String[] args) throws Exception {
        EssaludScrapper scrapper = new EssaludScrapper("fturconi", "ostk2004", 15);
        scrapper.getData(1, "71012668");
        scrapper.close();
    }
}

