
package com.affirm.equifax.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CreditReportPortService", targetNamespace = "http://impl.endpoint.creditreport.ws.equifax.com.pe/", wsdlLocation = "https://ws.equifax.com.pe/CreditReportService/Endpoint?wsdl")
public class CreditReportPortService
    extends Service
{

    private final static URL CREDITREPORTPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITREPORTPORTSERVICE_EXCEPTION;
    private final static QName CREDITREPORTPORTSERVICE_QNAME = new QName("http://impl.endpoint.creditreport.ws.equifax.com.pe/", "CreditReportPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(System.getenv("EFX_URL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITREPORTPORTSERVICE_WSDL_LOCATION = url;
        CREDITREPORTPORTSERVICE_EXCEPTION = e;
    }

    public CreditReportPortService() {
        super(__getWsdlLocation(), CREDITREPORTPORTSERVICE_QNAME);
    }

    public CreditReportPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITREPORTPORTSERVICE_QNAME, features);
    }

    public CreditReportPortService(URL wsdlLocation) {
        super(wsdlLocation, CREDITREPORTPORTSERVICE_QNAME);
    }

    public CreditReportPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITREPORTPORTSERVICE_QNAME, features);
    }

    public CreditReportPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditReportPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Endpoint
     */
    @WebEndpoint(name = "CreditReportPort")
    public Endpoint getCreditReportPort() {
        return super.getPort(new QName("http://impl.endpoint.creditreport.ws.equifax.com.pe/", "CreditReportPort"), Endpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Endpoint
     */
    @WebEndpoint(name = "CreditReportPort")
    public Endpoint getCreditReportPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.endpoint.creditreport.ws.equifax.com.pe/", "CreditReportPort"), Endpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITREPORTPORTSERVICE_EXCEPTION!= null) {
            throw CREDITREPORTPORTSERVICE_EXCEPTION;
        }
        return CREDITREPORTPORTSERVICE_WSDL_LOCATION;
    }

}
