
package com.affirm.equifax.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EquifaxInterfaceException", targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint")
public class EquifaxInterfaceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EquifaxInterfaceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EquifaxInterfaceException_Exception(String message, EquifaxInterfaceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EquifaxInterfaceException_Exception(String message, EquifaxInterfaceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.affirm.equifax.ws.EquifaxInterfaceException
     */
    public EquifaxInterfaceException getFaultInfo() {
        return faultInfo;
    }

}
