package com.affirm.common.model.transactional;

import com.affirm.common.util.JsonUtil;
import org.json.JSONObject;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by john on 29/09/16.
 */
public class EssaludResult implements Serializable {
    public static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");

    private Integer queryId;
    private Integer inDocType;
    private String inDocNumber;
    private String fullName;
    private String documentNumber;
    private String inssuredType;
    private String autogeneratedID;
    private String inssuranceType;
    private String healthCenter;
    private String healthCenterAddress;
    private Date since;
    private Date until;
    private String afiliatedTo;

    public void fillFromDb(JSONObject json) {
        setQueryId(JsonUtil.getIntFromJson(json, "query_id", null));
        setInDocType(JsonUtil.getIntFromJson(json, "in_document_type", null));
        setInDocNumber(JsonUtil.getStringFromJson(json, "in_document_number", null));
        setFullName(JsonUtil.getStringFromJson(json, "full_name", null));
        setDocumentNumber(JsonUtil.getStringFromJson(json, "document_number", null));
        setInssuredType(JsonUtil.getStringFromJson(json, "inssured_type", null));
        setAutogeneratedID(JsonUtil.getStringFromJson(json, "autogenerated_id", null));
        setInssuranceType(JsonUtil.getStringFromJson(json, "inssurance_type", null));
        setHealthCenter(JsonUtil.getStringFromJson(json, "health_center", null));
        setHealthCenterAddress(JsonUtil.getStringFromJson(json, "health_center_address", null));
        setSince(JsonUtil.getPostgresDateFromJson(json, "valid_since", null));
        setUntil(JsonUtil.getPostgresDateFromJson(json, "valid_until", null));
        setAfiliatedTo(JsonUtil.getStringFromJson(json, "afiliated_to", null));
    }

    public Integer getQueryId() {
        return queryId;
    }

    public void setQueryId(Integer queryId) {
        this.queryId = queryId;
    }

    public Integer getInDocType() {
        return inDocType;
    }

    public void setInDocType(Integer inDocType) {
        this.inDocType = inDocType;
    }

    public String getInDocNumber() {
        return inDocNumber;
    }

    public void setInDocNumber(String inDocNumber) {
        this.inDocNumber = inDocNumber;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getDocumentNumber() {
        return documentNumber;
    }

    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }

    public String getInssuredType() {
        return inssuredType;
    }

    public void setInssuredType(String inssuredType) {
        this.inssuredType = inssuredType;
    }

    public String getAutogeneratedID() {
        return autogeneratedID;
    }

    public void setAutogeneratedID(String autogeneratedID) {
        this.autogeneratedID = autogeneratedID;
    }

    public String getInssuranceType() {
        return inssuranceType;
    }

    public void setInssuranceType(String inssuranceType) {
        this.inssuranceType = inssuranceType;
    }

    public String getHealthCenter() {
        return healthCenter;
    }

    public void setHealthCenter(String healthCenter) {
        this.healthCenter = healthCenter;
    }

    public String getHealthCenterAddress() {
        return healthCenterAddress;
    }

    public void setHealthCenterAddress(String healthCenterAddress) {
        this.healthCenterAddress = healthCenterAddress;
    }

    public Date getSince() {
        return since;
    }

    public void setSince(Date since) {
        this.since = since;
    }

    public Date getUntil() {
        return until;
    }

    public void setUntil(Date until) {
        this.until = until;
    }

    public String getAfiliatedTo() {
        return afiliatedTo;
    }

    public void setAfiliatedTo(String afiliatedTo) {
        this.afiliatedTo = afiliatedTo;
    }

    @Override
    public String toString() {
        return "EssaludResult{" + "fullName=" + fullName + ", documentNumber=" + documentNumber + ", inssuredType=" + inssuredType + ", autogeneratedID=" + autogeneratedID + ", inssuranceType=" + inssuranceType + ", healthCenter=" + healthCenter + ", healthCenterAddress=" + healthCenterAddress + ", since=" + since + ", until=" + until + ", afiliatedTo=" + afiliatedTo + '}';
    }
}
