
package com.affirm.iovation.ws.transaction.check;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortType", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param subscriberaccount
     * @param reason
     * @param endblackbox
     * @param subscriberid
     * @param subscriberpasscode
     * @param type
     * @param result
     * @param txnProperties
     * @param enduserip
     * @param trackingnumber
     * @param details
     * @param beginblackbox
     * @param accountcode
     */
    @WebMethod(operationName = "CheckTransactionDetails", action = "http://www.iesnare.com/dra/api/CheckTransactionDetails#CheckTransactionDetails")
    @RequestWrapper(localName = "CheckTransactionDetails", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", className = "com.affirm.iovation.ws.transaction.check.CheckTransactionDetails")
    @ResponseWrapper(localName = "CheckTransactionDetailsResponse", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", className = "com.affirm.iovation.ws.transaction.check.CheckTransactionDetailsResponse")
    public void checkTransactionDetails(
        @WebParam(name = "subscriberid", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String subscriberid,
        @WebParam(name = "subscriberaccount", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String subscriberaccount,
        @WebParam(name = "subscriberpasscode", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String subscriberpasscode,
        @WebParam(name = "enduserip", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String enduserip,
        @WebParam(name = "accountcode", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String accountcode,
        @WebParam(name = "beginblackbox", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String beginblackbox,
        @WebParam(name = "type", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        String type,
        @WebParam(name = "txn_properties", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails")
        com.affirm.iovation.ws.transaction.check.CheckTransactionDetails.TxnProperties txnProperties,
        @WebParam(name = "result", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", mode = WebParam.Mode.OUT)
        Holder<String> result,
        @WebParam(name = "reason", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", mode = WebParam.Mode.OUT)
        Holder<String> reason,
        @WebParam(name = "trackingnumber", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", mode = WebParam.Mode.OUT)
        Holder<String> trackingnumber,
        @WebParam(name = "endblackbox", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", mode = WebParam.Mode.OUT)
        Holder<String> endblackbox,
        @WebParam(name = "details", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", mode = WebParam.Mode.OUT)
        Holder<com.affirm.iovation.ws.transaction.check.CheckTransactionDetailsResponse.Details> details);

}
