
package com.affirm.iovation.ws.transaction.check;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://www.iesnare.com/dra/api/CheckTransactionDetails", wsdlLocation = "https://ci-snare.iovation.com/v1/CheckTransactionDetails.wsdl")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://www.iesnare.com/dra/api/CheckTransactionDetails", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            ClassLoader classloader = Thread.currentThread().getContextClassLoader();
            url = classloader.getResource("/com/affirm/iovation/ws/transaction/check/iovation.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public Service() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "CheckTransactionDetails")
    public PortType getCheckTransactionDetails() {
        return super.getPort(new QName("http://www.iesnare.com/dra/api/CheckTransactionDetails", "CheckTransactionDetails"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "CheckTransactionDetails")
    public PortType getCheckTransactionDetails(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.iesnare.com/dra/api/CheckTransactionDetails", "CheckTransactionDetails"), PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
