
package com.affirm.qapaq.model;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_ExternoSolven", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://qaalianzas.qapaq.pe/Ws_ESolven/WS_ExternoSolven.asmx?wsdl")
public class WSExternoSolven
    extends Service
{

    private final static URL WSEXTERNOSOLVEN_WSDL_LOCATION;
    private final static WebServiceException WSEXTERNOSOLVEN_EXCEPTION;
    private final static QName WSEXTERNOSOLVEN_QNAME = new QName("http://tempuri.org/", "WS_ExternoSolven");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://qaalianzas.qapaq.pe/Ws_ESolven/WS_ExternoSolven.asmx?wsdl");
            url = new URL(System.getenv("QAPAQ_URL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSEXTERNOSOLVEN_WSDL_LOCATION = url;
        WSEXTERNOSOLVEN_EXCEPTION = e;
    }

    public WSExternoSolven() {
        super(__getWsdlLocation(), WSEXTERNOSOLVEN_QNAME);
    }

    public WSExternoSolven(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSEXTERNOSOLVEN_QNAME, features);
    }

    public WSExternoSolven(URL wsdlLocation) {
        super(wsdlLocation, WSEXTERNOSOLVEN_QNAME);
    }

    public WSExternoSolven(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSEXTERNOSOLVEN_QNAME, features);
    }

    public WSExternoSolven(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSExternoSolven(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSExternoSolvenSoap
     */
    @WebEndpoint(name = "WS_ExternoSolvenSoap")
    public WSExternoSolvenSoap getWSExternoSolvenSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WS_ExternoSolvenSoap"), WSExternoSolvenSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSExternoSolvenSoap
     */
    @WebEndpoint(name = "WS_ExternoSolvenSoap")
    public WSExternoSolvenSoap getWSExternoSolvenSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WS_ExternoSolvenSoap"), WSExternoSolvenSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSEXTERNOSOLVEN_EXCEPTION!= null) {
            throw WSEXTERNOSOLVEN_EXCEPTION;
        }
        return WSEXTERNOSOLVEN_WSDL_LOCATION;
    }

}
