
package com.affirm.qapaq.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_ExternoSolvenSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSExternoSolvenSoap {


    /**
     * 
     * @param opt
     * @param llave
     * @param identificacion
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "B_CapturarValor", action = "http://tempuri.org/B_CapturarValor")
    @WebResult(name = "B_CapturarValorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "B_CapturarValor", targetNamespace = "http://tempuri.org/", className = "com.affirm.qapaq.model.BCapturarValor")
    @ResponseWrapper(localName = "B_CapturarValorResponse", targetNamespace = "http://tempuri.org/", className = "com.affirm.qapaq.model.BCapturarValorResponse")
    public String bCapturarValor(
        @WebParam(name = "Opt", targetNamespace = "http://tempuri.org/")
        String opt,
        @WebParam(name = "Identificacion", targetNamespace = "http://tempuri.org/")
        String identificacion,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Llave", targetNamespace = "http://tempuri.org/")
        String llave);

}
